import json
from copy import deepcopy
from pathlib import Path

import promptabi
from promptabi import (
    MAINTAINER_FILENAMES,
    MAINTAINER_REFRESH_VERSION,
    diff_maintainer_snapshots,
    render_maintainer_release_notes,
)
from promptabi.cli import main


def test_maintainer_refresh_writes_real_corpus_artifacts(tmp_path: Path) -> None:
    refresh = promptabi.refresh_maintainer_tooling(tmp_path / "maintainer", force=True)

    assert {path.name for path in refresh.written_files} == set(MAINTAINER_FILENAMES)
    assert refresh.snapshot["manifest_version"] == MAINTAINER_REFRESH_VERSION
    assert refresh.snapshot["corpus_verification"]["ok"] is True
    assert refresh.snapshot["corpora"]["seed-corpus"]["count"] >= 10
    assert refresh.snapshot["corpora"]["provider-fixtures"]["count"] >= 6
    assert refresh.snapshot["expected_diagnostics"]["diagnostic_count"] > 0
    assert refresh.diff["status"] == "initial"

    notes = (tmp_path / "maintainer" / "release-notes.md").read_text(encoding="utf-8")
    assert "model-artifact manifests" not in notes
    assert "PromptABI maintainer release notes" in notes
    assert "Generated by `promptabi maintain refresh`" in notes


def test_expected_diagnostics_are_repo_relative_and_stable(tmp_path: Path) -> None:
    refresh = promptabi.refresh_maintainer_tooling(tmp_path / "maintainer", force=True)
    expected = json.loads((tmp_path / "maintainer" / "expected-diagnostics.json").read_text(encoding="utf-8"))

    assert expected["config_count"] >= 10
    assert len(expected["baseline_sha256"]) == 64

    seen_fingerprints = set()
    for config_entry in expected["configs"]:
        assert not Path(config_entry["config"]).is_absolute()
        for diagnostic in config_entry["diagnostics"]:
            fingerprint = diagnostic["fingerprint"]
            assert len(fingerprint) == 16
            seen_fingerprints.add(fingerprint)
            span = diagnostic["span"]
            if span is not None:
                assert not Path(span["path"]).is_absolute()
                assert "\\" not in span["path"]
            artifact = diagnostic["artifact"]
            if artifact is not None and "path" in artifact:
                assert not Path(artifact["path"]).is_absolute()
                assert "\\" not in artifact["path"]

    assert len(seen_fingerprints) == expected["diagnostic_count"]
    assert refresh.snapshot["expected_diagnostics"]["baseline_sha256"] == expected["baseline_sha256"]


def test_maintainer_diff_and_release_notes_report_check_changes(tmp_path: Path) -> None:
    refresh = promptabi.refresh_maintainer_tooling(tmp_path / "maintainer", force=True)
    baseline = deepcopy(refresh.snapshot)
    current = deepcopy(refresh.snapshot)
    current["corpora"]["seed-corpus"]["entries"]["llama"] = "changed-fixture-hash"
    current["expected_diagnostics"]["configs"][0]["rule_ids"].append("new-rule")
    current["expected_diagnostics"]["configs"][0]["diagnostic_count"] += 1

    diff = diff_maintainer_snapshots(baseline, current)
    notes = render_maintainer_release_notes(diff, current)

    assert diff["status"] == "changed"
    assert diff["corpora"][0]["corpus"] == "seed-corpus"
    assert "llama" in diff["corpora"][0]["changed"]
    assert diff["diagnostics"][0]["added"] == ["new-rule"]
    assert "Expected diagnostic changes" in notes
    assert "new-rule" not in notes


def test_maintain_refresh_cli_writes_baselined_diff(tmp_path: Path, capsys) -> None:
    baseline = tmp_path / "baseline"
    current = tmp_path / "current"
    promptabi.refresh_maintainer_tooling(baseline, force=True)

    exit_code = main(["maintain", "refresh", "--output-dir", str(current), "--baseline", str(baseline), "--force"])
    captured = capsys.readouterr()
    diff = json.loads((current / "corpus-diff.json").read_text(encoding="utf-8"))
    notes = (current / "release-notes.md").read_text(encoding="utf-8")

    assert exit_code == 0
    assert captured.err == ""
    assert "wrote maintainer refresh artifacts" in captured.out
    assert diff["status"] == "unchanged"
    assert "No corpus, fixture, diagnostic, or release-gate changes" in notes
