"""Public API for PromptABI.

PromptABI verifies the discrete interface layer around LLM systems: prompts,
chat templates, tokenizer metadata, stop policies, schemas, tools, and
framework budget contracts. The initial package exposes stable typed building
blocks that later checkers can reuse without changing the embedding API.
"""

from ._version import __version__
from .artifacts import (
    ArtifactBundle,
    ArtifactKind,
    ArtifactLocation,
    ArtifactProvenance,
    ChatTemplateArtifact,
    FrameworkTruncationConfigArtifact,
    GrammarArtifact,
    PromptSegment,
    PromptSegmentArtifact,
    ProviderConfigArtifact,
    SchemaArtifact,
    SpecialToken,
    SpecialTokenMapArtifact,
    StopPolicyArtifact,
    TokenizerArtifact,
    ToolDefinitionArtifact,
    TruncationStrategy,
)
from .config import ConfigError, VerificationConfig, discover_config, load_config
from .diagnostics import (
    ArtifactRef,
    Diagnostic,
    DiagnosticSeverity,
    SourceSpan,
    WitnessStep,
    WitnessTrace,
)
from .loaders import ArtifactLoadError, ArtifactLoader, ArtifactLoadWarning, LoadedArtifact, load_artifact
from .session import VerificationResult, VerificationSession
from .tokenizers import (
    ByteLevelTokenizer,
    DecodeResult,
    EncodedToken,
    EncodeResult,
    HuggingFaceTokenizerAdapter,
    NormalizationRule,
    RoundTripResult,
    SentencePieceAdapter,
    TiktokenAdapter,
    TokenizerAdapter,
    TokenizerBackend,
    TokenizerError,
    apply_normalization,
    load_tokenizer,
)

__all__ = [
    "__version__",
    "ArtifactBundle",
    "ArtifactKind",
    "ArtifactLocation",
    "ArtifactLoadError",
    "ArtifactLoadWarning",
    "ArtifactLoader",
    "ArtifactProvenance",
    "ArtifactRef",
    "ChatTemplateArtifact",
    "ConfigError",
    "ByteLevelTokenizer",
    "DecodeResult",
    "Diagnostic",
    "DiagnosticSeverity",
    "EncodedToken",
    "EncodeResult",
    "FrameworkTruncationConfigArtifact",
    "GrammarArtifact",
    "HuggingFaceTokenizerAdapter",
    "LoadedArtifact",
    "NormalizationRule",
    "PromptSegment",
    "PromptSegmentArtifact",
    "ProviderConfigArtifact",
    "RoundTripResult",
    "SchemaArtifact",
    "SentencePieceAdapter",
    "SourceSpan",
    "SpecialToken",
    "SpecialTokenMapArtifact",
    "StopPolicyArtifact",
    "TiktokenAdapter",
    "TokenizerArtifact",
    "TokenizerAdapter",
    "TokenizerBackend",
    "TokenizerError",
    "ToolDefinitionArtifact",
    "TruncationStrategy",
    "VerificationConfig",
    "VerificationResult",
    "VerificationSession",
    "WitnessStep",
    "WitnessTrace",
    "apply_normalization",
    "discover_config",
    "load_artifact",
    "load_config",
    "load_tokenizer",
]
